version: "3.7"
networks:
    default:
        name: wikiforest
services:
    web:
        image: nginx:latest
        restart: always
        volumes:
            - ./deploy/nginx/templates:/etc/nginx/templates
            - ./deploy/nginx/logs:/web/logs/nginx
            - .:/opt/www
        expose:
            - 80
        environment:
            NGINX_PORT: ${DOCKER_WEB_PORT}
            VIRTUAL_HOST: wikiforest.com
    server:
        build:
            context: ./deploy/docker/
            dockerfile: Dockerfile.${DOCKER_UI_ENV}
        container_name: wiki_ui_nextjs
        image: wikiforest/nextjs:${DOCKER_UI_IMAGE_TAB}
        restart: always
        tty: true
        expose:
            - 3000
        volumes:
            - .:/opt/www
