FROM node:14-alpine3.10

COPY . /opt/www

WORKDIR /opt/www

RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.aliyun.com/g' /etc/apk/repositories \
    && yarn \
    && yarn build

EXPOSE 3000

ENTRYPOINT ["yarn", "start"]
